# Generated by Django 4.2.11 on 2024-05-09 19:40

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('n_projeto', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_projeto', models.TextField()),
                ('n_sei', models.IntegerField()),
                ('n_empenho', models.CharField(max_length=255)),
                ('data_solicitacao', models.DateField()),
                ('status_projeto', models.CharField(max_length=255)),
                ('n_termoaceite', models.CharField(max_length=255)),
                ('reponsavel_termo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=255)),
                ('precisa_redefinir_senha', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='usuario_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='usuario_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('n_parcelas', models.PositiveSmallIntegerField()),
                ('status_pagamento', models.TextField()),
                ('descricao', models.TextField()),
                ('n_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id_operacao', models.IntegerField(primary_key=True, serialize=False)),
                ('data_operacao', models.DateField()),
                ('status_operacao', models.CharField(max_length=255)),
                ('nome_operacao', models.CharField(max_length=255)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
                ('n_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projeto')),
            ],
        ),
    ]
