# Generated by Django 4.2.11 on 2024-05-02 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('n_projeto', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_projeto', models.TextField()),
                ('n_sei', models.IntegerField()),
                ('n_empenho', models.CharField(max_length=255)),
                ('data_solicitacao', models.DateField()),
                ('status_projeto', models.CharField(max_length=255)),
                ('n_termoaceite', models.CharField(max_length=255)),
                ('reponsavel_termo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('n_parcelas', models.PositiveSmallIntegerField()),
                ('status_pagamento', models.TextField()),
                ('descricao', models.TextField()),
                ('n_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id_operacao', models.IntegerField(primary_key=True, serialize=False)),
                ('data_operacao', models.DateField()),
                ('status_operacao', models.CharField(max_length=255)),
                ('nome_operacao', models.CharField(max_length=255)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
                ('n_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projeto')),
            ],
        ),
    ]
