# Generated by Django 4.2.11 on 2024-05-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status_pagamento',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_solicitacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='n_empenho',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='n_termoaceite',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='reponsavel_termo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status_projeto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
