# Generated by Django 4.2.11 on 2024-05-19 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pagamento_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operacao',
            name='id_operacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
