# Generated by Django 4.2.11 on 2024-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_operacao_id_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='n_empenho',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='n_sei',
            field=models.CharField(max_length=21),
        ),
    ]
