# Generated by Django 4.2.11 on 2024-05-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_operacao_data_cadastro_alter_operacao_id_operacao'),
        ('home', '0006_operacao_data_cadastro'),
    ]

    operations = [
    ]
