# Generated by Django 4.2.11 on 2024-05-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20240522_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='n_parcelas_pagas',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
